// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe_riUH0d9hv4pLNPcrsO-HIu6YHTjfec',
    appId: '1:79179413535:web:0c966791497414fa14bd2a',
    messagingSenderId: '79179413535',
    projectId: 'modul6-a6f8c',
    authDomain: 'modul6-a6f8c.firebaseapp.com',
    storageBucket: 'modul6-a6f8c.appspot.com',
    measurementId: 'G-9H6TXEHCV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnpVAv_CJFCys8SQcK5PzDc0gbDQMOqd4',
    appId: '1:79179413535:android:c4ba9047ae2314c514bd2a',
    messagingSenderId: '79179413535',
    projectId: 'modul6-a6f8c',
    storageBucket: 'modul6-a6f8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhcsgPlSYL3hkWxbmiGvPQwCpquN-B0jo',
    appId: '1:79179413535:ios:490f1c9d8241a6fe14bd2a',
    messagingSenderId: '79179413535',
    projectId: 'modul6-a6f8c',
    storageBucket: 'modul6-a6f8c.appspot.com',
    iosBundleId: 'com.example.modul6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhcsgPlSYL3hkWxbmiGvPQwCpquN-B0jo',
    appId: '1:79179413535:ios:dd76cd4db8b1d44e14bd2a',
    messagingSenderId: '79179413535',
    projectId: 'modul6-a6f8c',
    storageBucket: 'modul6-a6f8c.appspot.com',
    iosBundleId: 'com.example.modul6.RunnerTests',
  );
}
